services:
  frontend:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    command: >
      /bin/sh -c "
      chmod -R 755 /usr/share/nginx/html && 
      nginx -g 'daemon off;'
      "